@API_HostAddress = https://localhost:7186

@id=3
DELETE {{API_HostAddress}}/api/tag?id={{id}}

###

GET {{API_HostAddress}}/api/achivement

###

GET {{API_HostAddress}}/api/hobby

###

POST {{API_HostAddress}}/api/achivement
Content-Type: application/json

{
  //Achivement
}

###
