@CVproject.api_HostAddress = https://localhost:44344

GET {{CVproject.api_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{CVproject.api_HostAddress}}/api/hobby

###

@id=0
DELETE {{CVproject.api_HostAddress}}/api/hobby/{{id}}

###

POST {{CVproject.api_HostAddress}}/api/hobby
Content-Type: application/json

{
  //Hobby
}

###

PATCH {{CVproject.api_HostAddress}}/api/hobby/{id}
Content-Type: application/json

{
  //Hobby
}

###

POST {{CVproject.api_HostAddress}}/api/user/login
Content-Type: application/json

{
  //LoginDto
}

###

POST {{CVproject.api_HostAddress}}/api/user/register
Content-Type: application/json

{
  //RegisterDto
}

###

GET {{CVproject.api_HostAddress}}/api/hobby

###

DELETE {{CVproject.api_HostAddress}}/api/project/{{id}}

###

POST {{CVproject.api_HostAddress}}/api/hobby
Content-Type: application/json

{
  //Hobby
}

###

GET {{CVproject.api_HostAddress}}/api/hobby

###

GET {{CVproject.api_HostAddress}}/api/achivement

###

GET {{CVproject.api_HostAddress}}/api/project

###

POST {{CVproject.api_HostAddress}}/api/project
Content-Type: application/json

{
  //Project
}

###

POST {{CVproject.api_HostAddress}}/api/projecttags
Content-Type: application/json

{
  //ProjectTags
}

###

POST {{CVproject.api_HostAddress}}/api/tag
Content-Type: application/json

{
  //Tag
}

###
